services:
    sasedev_form_entityid.form.type.entityid:
        class: Sasedev\Form\EntityidBundle\Form\Type\EntityidType
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: entityid }
