parameters:
    sasedev_form_entityid.form.type.entityid.class: Sasedev\Form\EntityidBundle\Form\Type\EntityidType

services:
    sasedev_form_entityid.form.type.entityid:
        class: %sasedev_form_entityid.form.type.entityid.class%
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: entityid }
